name: 'Walalalala'

on:
  push:
    branches:
      - "*"

jobs:
  change-files-checks:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2