name: 'File Changes'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  change-files-checks:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changes in internationalisation_de
        run: |
          # Assuming internationalisation_de_DE.json is the file you're interested in
          file_path="CMS/internationalisation_de_DE.json"

          # Get the added and removed lines
          added_lines=$(git diff --cached --unified=0 "$file_path" | grep '^\+' | sed 's/^\+//')
          removed_lines=$(git diff --unified=0 "$file_path" | grep '^\-' | sed 's/^\-//')

          echo "Added lines:"
          echo "$added_lines"
          
          echo "Removed lines:"
          echo "$removed_lines"
