name: 'File Changes'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  change-files-checks:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changes in internationalisation_de
        run: |
          added_changes=$(git diff --cached --name-only | xargs git diff --cached --)
          removed_changes=$(git diff --name-only | xargs git show)
          
          echo "Added changes:"
          echo "$added_changes"
          
          echo "Removed changes:"
          echo "$removed_changes"
