name: 'File Changes'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  change-files-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
             **.json

      - name: Run JavaScript comparison
        run: |
          added_changes=()  # Initialize an empty array
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            echo "Changes in $file:"
            # Get the content of the file in the base branch (usually main or master)
            base_content=$(git show origin/main:"$file")
            
            # Get the content of the file in the current branch
            current_content=$(cat "$file")
            
            # Run the JavaScript comparison function
            changed_lines=$(node compareFiles.js "$base_content" "$current_content")

            # Print the changed lines
            echo "$changed_lines"
          done

