name: Extract Added Lines

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract-added-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Extract added lines
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "$branch"
