name: Extract Added Lines

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract-added-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Extract added lines
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "$branch"
          
          # Fetch the latest changes from the remote repository
          git fetch origin main
          git fetch origin $branch
          
          # Get the added lines between origin/main and origin/$branch
          added_lines=($(git diff origin/main..origin/$branch -- CMS/internationalisation_de_DE.json | grep '^+' | sed 's/^+ //' | tr '\n' ' '))
          
          # Get the removed lines between origin/main and origin/$branch
          removed_lines=($(git diff origin/main..origin/$branch -- CMS/internationalisation_de_DE.json | grep '^-' | sed 's/^- //' | tr '\n' ' '))

          # Use $added_lines and $removed_lines variables in subsequent steps or print them
          echo "Added lines:"
          for line in "${added_lines[@]}"; do
            echo "$line"
          done

          echo "Removed lines:"
          for line in "${removed_lines[@]}"; do
            echo "$line"
          done
