name: Extract Added Lines

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract-added-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Extract added lines
        run: |
          added_lines=$(git diff develop...${{ github.event.before }} -- CMS/internationalisation_de_DE.json | grep '^+' | tail -n +2 | sed 's/^+ //')

          # Use $added_lines variable in subsequent steps or print it
          echo "$added_lines"
