name: Extract Added Lines

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract-added-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Extract added lines
        run: |
          echo "${{ GITHUB_HEAD_REF }}"
          added_lines=$(git diff --name-only origin/main origin/${GITHUB_HEAD_REF})

          # Use $added_lines variable in subsequent steps or print it
          echo "$added_lines"
