name: 'Add CMS Changes to CMS Project'
on:
  push:
    branches:
      - main

env:
  GITHUB_EVENT_BEFORE: ${{ github.event.before }}
  GITHUB_SHA: ${{ github.sha }}

jobs:
  core-commits-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run cms check
        id: 'run-cms-check'
        run: |
          # Get the differences between github.event.before and github.sha
          CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Print the changes
          echo "Changes in this commit:"
          echo "$CHANGES"

      - name: Create Issue From File
        id: create-issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: An example issue
          content-filepath: ./issue-template.md
          labels: |
            report
