name: Extract Added Lines

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract-added-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Extract added lines
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "$branch"
          
          # Fetch the latest changes from the remote repository
          git fetch origin main
          git fetch origin $branch
          
          # Get the added lines between origin/main and origin/$branch
          added_lines=$(git diff origin/main..origin/$branch -- CMS/internationalisation_de_DE.json | grep '^+' | tail -n +2 | sed 's/^+ //' | sed 's/,$//')
          removed_lines=$(git diff origin/main..origin/$branch -- CMS/internationalisation_de_DE.json | grep '^-' | tail -n +2 | sed 's/^- //' | sed 's/,$//')

          # Check if both added_lines and removed_lines are not empty before proceeding
          if [ -n "$added_lines" ] && [ -n "$removed_lines" ]; then
            echo "And Gowaaaaa"
            # Check if added_lines is not empty before sorting
            added_lines=$(echo "$added_lines" | sort)

            # Check if removed_lines is not empty before sorting
            removed_lines=$(echo "$removed_lines" | sort)

            # Use comm to find common lines between added_lines and removed_lines
            common_lines=$(comm -12 <(echo "$added_lines") <(echo "$removed_lines") || true)

            # Remove common lines from added_lines and removed_lines
            added_lines=$(grep -vFf <(echo "$common_lines") <(echo "$added_lines"))
            removed_lines=$(grep -vFf <(echo "$common_lines") <(echo "$removed_lines"))
          fi

          echo "Added Lines:"
          echo "$added_lines"
          echo "Removed Lines:"
          echo "$removed_lines"
