name: 'File Changes'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  change-files-checks:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get all changed json files
        id: changed-json-files
        run: |
          # Get all changed json files
          changed_json_files=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.json'))
          echo "::set-output name=changed_json_files::${changed_json_files[*]}"

      - name: Print added changes in json files
        id: print-changes
        run: |
          added_changes=()  # Initialize an empty array
          for file in ${{ steps.changed-json-files.outputs.changed_json_files }}; do
            echo "Added changes in $file:"
            # Get the content of the file in the base branch (usually main or master)
            base_content=$(git show origin/main:"$file")
            
            # Get the content of the file in the current branch
            current_content=$(cat "$file")
            
            # Use diff to compare the contents and add lines with meaningful changes to the array
            while IFS= read -r line; do
              if [[ "$line" =~ ^\+[^+]{1,}$ && ! "$line" =~ ^\+{.*}$ ]]; then
                added_changes+=("${line:1}")  # Remove the leading '+'
              fi
            done < <(diff -u <(echo "$base_content") <(echo "$current_content") | grep '^\+')
            
            # Drop the first item in added_changes
            added_changes=("${added_changes[@]:1}")
            
            # Print all added changes
            for added_line in "${added_changes[@]}"; do
              echo "$added_line"
            done
          done

          # Set the output variable with the added changes
          echo "::set-output name=printed_changes::${added_changes[*]}"

      - name: Create new issue
        id: create-issue
        run: |
          title="Found a bug"
          body="${{ steps.print-changes.outputs.printed_changes//$'\n'/\\n }}"
          labels="[\"bug\"]"

          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/Mahmoudn1/github-action/issues \
            -d "{\"title\":\"$title\",\"body\":\"$body\",\"labels\":$labels}")

          echo "Issue creation response: $response"
