name: 'File Changes'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  change-files-checks:
    runs-on: ubuntu-latest
    permissions:
      issues: write   

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
             **.json

      - name: Print added changes in markdown files
        id: print-changes
        run: |
          added_changes=()  # Initialize an empty array
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            echo "Added changes in $file:"
            # Get the content of the file in the base branch (usually main or master)
            base_content=$(git show origin/main:"$file")
            
            # Get the content of the file in the current branch
            current_content=$(cat "$file")
            
            # Use diff to compare the contents and add lines with meaningful changes to the array
            while IFS= read -r line; do
              if [[ "$line" =~ ^\+[^+]{1,}$ && ! "$line" =~ ^\+{.*}$ ]]; then
                added_changes+=("${line:1}")  # Remove the leading '+'
              fi
            done < <(diff -u <(echo "$base_content") <(echo "$current_content") | grep '^\+')
            
            # Print all added changes
            for added_line in "${added_changes[@]}"; do
              echo "$added_line"
            done
          done

          # Set the output variable with the added changes
          echo "::set-output name=printed_changes::${added_changes[*]}"

      - name: Create new issue
        id: create-issue
        run: |
          echo "Added changes: ${{ steps.print-changes.outputs.printed_changes }}"
          title="Found a bug"
          removed_quotes=$(echo "${{ steps.print-changes.outputs.printed_changes }}"| tr -d '"')
          echo "$removed_quotes"
          body="$removed_quotes"
          labels="[\"bug\"]"

          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/Mahmoudn1/github-action/issues \
            -d "{\"title\":\"$title\",\"body\":\"$body\",\"labels\":$labels}")

          # Set the output variable
          issue_id=$(echo "$response" | jq -r '.node_id')
          echo "::set-output name=issue_id::${issue_id}"

      - name: Add Item to The Project
        id: add-item
        run: |
          echo "Added changes: ${{ steps.create-issue.outputs.issue_id }}"
          issue_id="${{ steps.create-issue.outputs.issue_id }}"
          response=$(curl --request POST \
            --url https://api.github.com/graphql \
            --header 'Authorization: Bearer ${{ secrets.MY_SECRET }}' \
            --data '{"query":"mutation {addProjectV2ItemById(input: {projectId: \"PVT_kwHOBYJ8084AYkeK\" contentId: \"'"$issue_id"'\"}) {item {id}}}"}')
          
          echo "$response"
