name: 'File Changes'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  change-files-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
             **.json

      - name: Print added changes in markdown files
        run: |
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            echo "Added changes in $file:"
            # Get the content of the file in the base branch (usually main or master)
            base_content=$(git show origin/main:"$file")
            
            # Get the content of the file in the current branch
            current_content=$(cat "$file")
            
            # Use diff to compare the contents and print lines with meaningful changes
            added_changes=$(diff -u <(echo "$base_content") <(echo "$current_content") | grep '^\+' | sed 's/^+//' | grep -v '^{.*}$' | sed '1d')
            
            # Print all added changes excluding lines with only braces and excluding the first line
            echo "$added_changes"
          done
