# .github/workflows/workflow.yml
name: 'Add changes in internationalisation_de_DE to Github Project'

on:
  push:
    branches:
      - main

jobs:
  change-files-checks:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Extract modified lines
        id: extract-modified-lines
        run: ./scripts/extract-modified-lines.sh

      - name: Create new issue
        id: create-issue
        run: ./scripts/create-issue.sh

      - name: Add Item to The Project
        id: add-item
        run: ./scripts/add-item.sh
